# Generates pretty snake animation, using @Platane's awesome snk action
name: 🐍 Generate Snake Contribution
on:
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: '30 23 * * *' # Runs at 23:30 every day.
jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4.0.0
        with:
          ref: ${{ github.head_ref }}
      - name: Generate Snake
        uses: Platane/snk/svg-only@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-snake.svg
            assets/github-snake-dark.svg?palette=github-dark   
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Commit and push the changes
      - name: Publish package
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: ":snake: Updates Snake Contribution Animation"
          commit_user_name: FollowingAkash
          commit_user_email: bot@akashrajpurohit.com
          commit_author: FollowingAkash <bot@akashrajpurohit.com>
